# Messege that has a data related to velocity from ECU
bool ACC_Fd_EN
uint8 Mo_Fd_State
bool ACC_Fd_ErrBit_PD
bool ACC_Fd_ErrBit_TCU
bool ACC_Fd_ErrBit_ACC
uint8 Mo_Fd_Seq
bool Break_Pedal_Pushed
bool Accel_Pedal_Pushed
uint8 ACC_Fd_VSpeed     # vehicle's current speed
uint8 ACC_Fd_SetSpeed
float32 Long_Accel
uint8 Switch_Fd
bool ACC_Fd_Ovrrd_Rturn_sig
bool ACC_Fd_Ovrrd_Haz_sig
bool ACC_Fd_Ovrrd_Lturn_sig
uint8 G_Sel_Disp
uint8 Mo_Fd_AlvCnt
