// Generated by gencpp from file pcan/CanFrame.msg
// DO NOT EDIT!


#ifndef PCAN_MESSAGE_CANFRAME_H
#define PCAN_MESSAGE_CANFRAME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pcan
{
template <class ContainerAllocator>
struct CanFrame_
{
  typedef CanFrame_<ContainerAllocator> Type;

  CanFrame_()
    : timestamp()
    , ID(0)
    , Length(0)
    , Data()  {
    }
  CanFrame_(const ContainerAllocator& _alloc)
    : timestamp()
    , ID(0)
    , Length(0)
    , Data(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef uint32_t _ID_type;
  _ID_type ID;

   typedef uint8_t _Length_type;
  _Length_type Length;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _Data_type;
  _Data_type Data;




  typedef boost::shared_ptr< ::pcan::CanFrame_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pcan::CanFrame_<ContainerAllocator> const> ConstPtr;

}; // struct CanFrame_

typedef ::pcan::CanFrame_<std::allocator<void> > CanFrame;

typedef boost::shared_ptr< ::pcan::CanFrame > CanFramePtr;
typedef boost::shared_ptr< ::pcan::CanFrame const> CanFrameConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pcan::CanFrame_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pcan::CanFrame_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pcan

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'pcan': ['/home/youngbo/ave_can/can_ws/src/pcan/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pcan::CanFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pcan::CanFrame_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcan::CanFrame_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pcan::CanFrame_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcan::CanFrame_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pcan::CanFrame_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pcan::CanFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c5ce6510aecfcaf5ba4e423898f02f3";
  }

  static const char* value(const ::pcan::CanFrame_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c5ce6510aecfcafULL;
  static const uint64_t static_value2 = 0x5ba4e423898f02f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::pcan::CanFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pcan/CanFrame";
  }

  static const char* value(const ::pcan::CanFrame_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pcan::CanFrame_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time timestamp\n\
uint32 ID\n\
uint8 Length\n\
uint8[] Data\n\
";
  }

  static const char* value(const ::pcan::CanFrame_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pcan::CanFrame_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.ID);
      stream.next(m.Length);
      stream.next(m.Data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CanFrame_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pcan::CanFrame_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pcan::CanFrame_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "ID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ID);
    s << indent << "Length: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Length);
    s << indent << "Data[]" << std::endl;
    for (size_t i = 0; i < v.Data.size(); ++i)
    {
      s << indent << "  Data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.Data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCAN_MESSAGE_CANFRAME_H
