Header header

float32 v_ego        # Current speed of vehicle to x-axis
float32 a_x          # Acceleration of vehicle to x-axis
float32 yaw_rate     # Yaw rate(angular velocity)
float32 steer_angle  # Steering Wheel Angle

float32 x            # The x-coordinate of vehicle position.
float32 y            # The y-coordinate of vehicle position.
float32 heading      # The heading of vehicle position, which is the angle between the vehicle's heading direction and x-axis.
